# Generated by Django 4.1.1 on 2022-09-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selibraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
