# Generated by Django 4.1.1 on 2022-09-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selibraryapp', '0002_rename_messages_message'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='Reviews',
        ),
    ]
