# Generated by Django 4.1.1 on 2022-09-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selibraryapp', '0003_alter_message_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
