# Generated by Django 4.1.1 on 2022-09-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selibraryapp', '0008_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='file',
            new_name='image',
        ),
    ]
