# Generated by Django 4.1.1 on 2022-09-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selibraryapp', '0009_rename_file_upload_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='image',
            new_name='file',
        ),
    ]
