# Generated by Django 4.1.1 on 2022-09-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selibraryapp', '0010_rename_image_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.ImageField(default='pdf.png', upload_to='display'),
        ),
    ]
