# Generated by Django 4.1.1 on 2022-09-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selibraryapp', '0012_alter_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
