# Generated by Django 4.1.1 on 2022-09-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selibraryapp', '0013_alter_upload_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='upload',
            table=None,
        ),
    ]
