# Generated by Django 4.1.1 on 2022-09-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selibraryapp', '0015_upload_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='dp',
            field=models.ImageField(default='display/pdf.png', upload_to=''),
        ),
    ]
