# Generated by Django 4.1.1 on 2022-09-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selibraryapp', '0016_alter_upload_dp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='dp',
            new_name='image',
        ),
    ]
