# Generated by Django 4.1.1 on 2022-09-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selibraryapp', '0019_alter_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(default='display/images.png', upload_to=''),
        ),
    ]
