# Generated by Django 4.1.2 on 2022-11-07 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selibraryapp', '0022_alter_message_message'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='upload',
            table='Upload',
        ),
    ]
